### ISSUE TITLE
'obi new' fails if /opt/oblong is missing

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#61]
I installed obi on my laptop, and then the [obi-cpp](https://github.com/Oblong/obi-cpp) template. But `obi new cpp <project>` fails:

```
% obi new cpp hakuna
Traceback (most recent call last):
  File "/home/tom/.local/bin/obi", line 9, in <module>
    load_entry_point('oblong-obi==3.0.1', 'console_scripts', 'obi')()
  File "/home/tom/.local/lib/python2.7/site-packages/obi/obi.py", line 140, in main
    g_speak_home = get_g_speak_home(arguments)
  File "/home/tom/.local/lib/python2.7/site-packages/obi/obi.py", line 84, in get_g_speak_home
    items = [os.path.join(path, item) for item in os.listdir(path) if "g-speak" in item]
OSError: [Errno 2] No such file or directory: '/opt/oblong'
```

**Comment by jshrake** [comment]
There should be better error handling around the assumption that g-speak is installed.
