### ISSUE TITLE
CTRL+C to interrupt LLDB's inferior process kills LLDB, too

### ISSUE THREAD

**Issue by tomjakubowski** [Oblong/obi#66]
When running a program on OS X with `obi go --debug=lldb`, pressing CTRL+C in the terminal to interrupt the inferior process and bring up the LLDB prompt doesn't work. Instead, CTRL+C seems to interrupt the inferior process and then terminates LLDB.

I've attached a small project generated with the [cpp](https://github.com/Oblong/obi-cpp) template. To reproduce the issue, run `obi go --debug=lldb` and interrupt with CTRL+C. The expected behavior is that the inferior process is interrupted and LLDB's prompt appears. The actual behavior is that LLDB is terminated.

The log looks something like this:

```
[localhost] Executing task 'launch_task'
[localhost] local:  lldb -- build/testo
(lldb) target create "build/testo"
Current executable set to 'build/testo' (x86_64).
(lldb) run
Process 23841 launched: '/Users/tjakubowski/tmp/testo/build/testo' (x86_64)
!!! Parallel execution exception under host 'localhost':
Process localhost:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/obi/HEAD/libexec/vendor/lib/python2.7/site-packages/fabric/tasks.py", line 242, in inner
    submit(task.run(*args, **kwargs))
  File "/usr/local/Cellar/obi/HEAD/libexec/vendor/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/local/Cellar/obi/HEAD/libexec/vendor/lib/python2.7/site-packages/fabric/decorators.py", line 181, in inner
    return func(*args, **kwargs)
  File "/usr/local/Cellar/obi/HEAD/libexec/lib/python2.7/site-packages/obi/task/task.py", line 206, in launch_task
    env.background_run(launch_cmd)
  File "/usr/local/Cellar/obi/HEAD/libexec/vendor/lib/python2.7/site-packages/fabric/operations.py", line 1185, in local
    (stdout, stderr) = p.communicate()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 796, in communicate
    self.wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1384, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
Process 23841 stopped
* thread #1: tid = 0x10a4f01, 0x00007fff90e26db6 libsystem_kernel.dylib`__psynch_cvwait + 10, stop reason = signal SIGSTOP
    frame #0: 0x00007fff90e26db6 libsystem_kernel.dylib`__psynch_cvwait + 10
libsystem_kernel.dylib`__psynch_cvwait:
->  0x7fff90e26db6 <+10>: jae    0x7fff90e26dc0            ; <+20>
    0x7fff90e26db8 <+12>: movq   %rax, %rdi
    0x7fff90e26dbb <+15>: jmp    0x7fff90e217cd            ; cerror_nocancel
    0x7fff90e26dc0 <+20>: retq
(lldb) %                                                                        tjakubowski@
```

[testo.tar.gz](https://github.com/Oblong/obi/files/477482/testo.tar.gz)

**Comment by jshrake** [comment]
I'm able to reproduce the issue, but I thought at one point in this worked as expected.

**Comment by tomjakubowski** [comment]
Idea: for local runs, obi should replace its process rather than forking + then execing. For local runs, by the time the application has started obi is done doing anything useful anyway, so it might as well let itself be replaced.
